### PR TITLE
Add MR-Uplift Package

### PR DESCRIPTION
**Pull request by samcarlos**
I would like to include my MR-Uplift package. This package a models an uplift model for multiple response variables and evaluates tradeoffs between them. Thanks!

### CODE REVIEW

**Comment by rguo12** [comment]
Thanks Sam, I think we will probably create a subsection (under the "learning causal effects" section) for uplift modeling later, as methodologically it is kind of different from effect estimation, especially in term of the evaluation metrics. If you can contribute that for the repo it would also be nice.

Thanks,

Ruocheng

**Review by rguo12 — APPROVED** [review]

**Comment by samcarlos** [comment]
Thanks @rguo12! My understanding is that "Uplift Models" is just another way of saying heterogenous treatment effects or Individual treatment effect estimations. This package uses similar methodologically to estimation of the treatment effect as the BART Paper by Hill in that section.

How would you say uplift models are distinct from HETE or ICE models?
Thanks,
Sam

**Comment by rguo12** [comment]
You are right, they are essentially the same problem, with CATE accurately
estimated, the problem is solved. Just like in offline policy evaluation,
if you estimate counterfactual outcomes/CATE correctly, the problem is
solved, although it is recommended to be solved by doubly robust
estimators, that is to emphasize the importance of propensity score
modeling in the offline policy evaluation problem.

Maybe I did not read many uplift modeling papers, but IMO uplift modeling
often evaluates models with the uplift curves or Qini curves where you
check the gain of assigning treatments to arbitrary subpopulations
(percentiles). The x axis is interesting here as it sorts instances
according to the causal effects. Looking at those curves, maybe the focus
is to develop a strategy to assign treatments when we only can assign
treatments to a limited amount of people.

Please correct me if I am wrong, since I have not read many uplift modeling
papers.

Best regards,

Ruocheng

**Comment by samcarlos** [comment]
Hey Ruocheng, 

Yea I think you're right. My understanding that a bunch of different domains solved ITE problems separately and came up with different terminology. Kind of like how some people say 'feature' and others say 'independent variable'. The use cases might be slightly different but the tools and general theory is widely applicable between them. 

Thanks,
Sam

**Comment by rguo12** [comment]
Thanks Sam, it is very nice to discuss with you. I will keep updating the
repo when I have time. I really appreciate your contribution.

Best regards,

Ruocheng

**Comment by samcarlos** [comment]
Nice talking with you Ruocheng. Thanks!

**Pull request merged**
